Week7 assignment done
zytfo/JavaScript-for-Enterprise-Development pull request #7
Opened 2019-03-23 18:48 UTC by zytfo

2019-04-06 19:28 UTC, kos33rd requested changes
Предлагаю избавиться от работы с внутренним state в `ItemsList`, после чего будем считать, что задания 7 и 8 недели выполнены.

2019-04-06 19:28 UTC, kos33rd commented on src/components/app-bar.js
> +    operationsCountFromRedux: state.data.length
Излишнее уточнение `FromRedux` - это технические детали.

2019-04-06 19:28 UTC, kos33rd commented on src/components/grid.js
> +import React from 'react'
Хм...
На самом деле, самописный `<Grid/>` - это упражнение на изучение css flexbox, нет нужны копипастить его из учебного репозитория - функциональность у Grid из Material UI больше.

2019-04-06 19:28 UTC, kos33rd commented on src/components/items-list.js
> +    state = {
Смешивать локальный state и state из redux - плохой паттерн.
Сам redux продвигает идею single source of truth, в которой для одних и тех же данных нет места в нескольких хранилищах.
У тебя есть возможность через mapStateToProps и mapDispatchToProps перенести всё состояние приложения в redux и получать его не через `this.state`, а через `this.props`.

2019-04-06 19:28 UTC, kos33rd commented on src/components/items-list.js
>          axios.get(`https://cors-anywhere.herokuapp.com/http://steamcommunity.com/profiles/${this.props.match.params.id}/inventory/json/440/2`)
Для выполнения задания 9 недели тебе потребуется вынести работу с внешним API в асинхронные action-ы redux.

2019-04-06 19:28 UTC, kos33rd commented on src/redux/actionCreators/index.js
> +    type: 'ITEMS_LIST_LOADED'
Опечатка в типе action-а.

2019-04-06 19:39 UTC, zytfo commented on src/components/grid.js
> +import React from 'react'
Да, знаю, просто интересно было побаловаться )

2019-04-06 20:14 UTC, zytfo commented on src/components/items-list.js
> +    state = {
Готово

2019-04-06 20:14 UTC, zytfo commented on src/components/items-list.js
>          axios.get(`https://cors-anywhere.herokuapp.com/http://steamcommunity.com/profiles/${this.props.match.params.id}/inventory/json/440/2`)
Понял, учту

2019-04-10 19:22 UTC, kos33rd approved these changes
Претензий нет, теперь для 8 недели всё ок.
Апрув 👍

2019-04-10 19:45 UTC, merged